Bongo/Areas/TimetableArea/Controllers/TimetableController.cs
using Bongo.Areas.TimetableArea.Infrastructure;
using Bongo.Areas.TimetableArea.Models;
using Bongo.Areas.TimetableArea.Models.ViewModels;
using Bongo.Data;
using Bongo.Models;
using Bongo.Services;
using iText.Kernel.Pdf;
using iText.Kernel.Pdf.Canvas.Parser;
using iText.Kernel.Pdf.Canvas.Parser.Listener;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Syncfusion.Drawing;
using Syncfusion.Pdf;
using Syncfusion.Pdf.Graphics;
using Syncfusion.Pdf.Grid;
using System.Text.RegularExpressions;
using PdfDocument = Syncfusion.Pdf.PdfDocument;
using PdfPage = Syncfusion.Pdf.PdfPage;

namespace Bongo.Areas.TimetableArea.Controllers
{
    [Authorize]
    [Area("TimetableArea")]
    public class TimetableController : Controller
    {
        private IRepositoryWrapper _repository;
        private readonly IMailService _mailSender;
        private readonly UserManager<BongoUser> _userManager;

        public TimetableController(IRepositoryWrapper repo, IMailService mailSender, UserManager<BongoUser> userManager)
        {
            _repository = repo;
            _mailSender = mailSender;
            _userManager = userManager;
        }

        #region Hepler Methods
        private IActionResult StartBlank()
        {
            Timetable table = new Timetable { TimetableText = "", Username = User.Identity.Name };
            _repository.Timetable.Update(table);
            _repository.SaveChanges();
            return RedirectToAction("Display");
        }
        public string GetTime(int i)
        {
            string starthourtime = (i + 7) > 9 ? (i + 7).ToString() : "0" + (i + 7).ToString();
            string endhourtime = (i + 8) > 9 ? (i + 8).ToString() : "0" + (i + 8).ToString();
            string time = $"{starthourtime}:00";
            time += Request.Cookies["isTimeSingle"].ToString() == "false" ? $" -{endhourtime}:00" : "";
            return time;
        }
        public void SetCookie(string key, string value)
        {
            CookieOptions cookieOptions = new CookieOptions { Expires = DateTime.Now.AddDays(90) };
            Response.Cookies.Append(key, value == null ? "" : value, cookieOptions);
        }
        #endregion


        [HttpGet]
        public IActionResult Display(int latestPeriod = 0)
        {

            if (Request.Cookies["isVenueHidden"] == null)
            {
                SetCookie("isVenueHidden", "false");
            }

            if (Request.Cookies["isTimeSingle"] == null)
            {
                SetCookie("isTimeSingle", "true");
            }

            bool isForFirstSemester = Request.Cookies["isForFirstSemester"] == "true";


            #region For Control
            List<List<Session>> ClashesList;
            List<Lecture> GroupedList;
            #endregion

            Timetable table = _repository.Timetable.GetUserTimetable(User.Identity.Name);
            if (table == null)
            {
                return RedirectToAction("Upload");
            }

            TimetableProcessor processor = new TimetableProcessor(table.TimetableText, isForFirstSemester);
            Session[,] data = processor.GetSessionsArray(out ClashesList, out GroupedList);

            if (ClashesList.Count > 0 || GroupedList.Count > 0)
            {
                return RedirectToAction("Manage", "Session");
            }

            ViewBag.isForFirstSemester = isForFirstSemester;
            TempData["isForFirstSemester"] = isForFirstSemester;
            IndexViewModel indexViewModel = new IndexViewModel
            {
                Sessions = data is not null ? data : new Session[5, 16],
                latestPeriod = latestPeriod
            };
            SetCookie("latestPeriod", indexViewModel.latestPeriod.ToString());
            return View(indexViewModel);
        }
        public IActionResult Upload()
        {
            Timetable table = _repository.Timetable.GetUserTimetable(User.Identity.Name);
            if (table != null)
                return RedirectToAction("Display", new { isForFirstSemester = true });
            return View();
        }

        [HttpPost]
        public IActionResult Upload(IFormFile file, string[] startBlank, bool isFirstSemester = true)
        {
            if (file != null)
            {
                if (file.Length < 500000) //revise
                {
                    if (file.ContentType == "application/pdf")
                    {
                        string text = "";
                        try
                        {
                            using (Stream stream = file.OpenReadStream())
                            {
                                //Read the text from a pdf file
                                using (iText.Kernel.Pdf.PdfDocument pdfDocument = new iText.Kernel.Pdf.PdfDocument(new PdfReader(stream)))
                                {

                                    // Extract text from each page
                                    for (int pageNumber = 1; pageNumber <= pdfDocument.GetNumberOfPages(); pageNumber++)
                                    {
                                        // Get the page using the page number
                                        iText.Kernel.Pdf.PdfPage page = pdfDocument.GetPage(pageNumber);

                                        // Create a new SimpleTextExtractionStrategy to extract text from the page
                                        LocationTextExtractionStrategy strategy = new LocationTextExtractionStrategy();

                                        // Extract text from the page
                                        string pageText = PdfTextExtractor.GetTextFromPage(page, strategy);

                                        // Append the extracted text from the page to the result
                                        text += pageText;
                                    }
                                }
                            }
                        }
                        catch (Exception)
                        {

                            ModelState.AddModelError("", "Something went wrong while uploading TimeTable. " +
                                "\n Please make sure your have uploaded the correct file.");
                            return View();
                        }

                        //Remove unwanted text
                        Regex patternTop = new Regex(@"(\d{4}) CLASS TIMETABLE\n(\d{10})");
                        Match match = patternTop.Match(text);
                        if (match.Success)
                        {
                            Regex pattern = new Regex(@"205 Nelson Mandela Drive  \|  Park West, Bloemfontein 9301 \| South Africa\nP\.O\. Box 339  \|  Bloemfontein 9300  \|  South Africa \| www\.ufs\.ac\.za|\nVenue Start End Day From To|Venue Start End Day From To\n");//|\(Group [A-Z]{1,2}\)|
                            text = pattern.Replace(text, String.Empty);

                            Timetable newTimetable = new Timetable { TimetableText = text, Username = User.Identity.Name };
                            _repository.Timetable.Update(newTimetable);
                            SessionControlHelpers.AddNewUserModuleColor(ref _repository, User.Identity.Name, newTimetable.TimetableText);
                            _repository.SaveChanges();


                            SetCookie("isForFirstSemester", isFirstSemester.ToString().ToLower());

                            return RedirectToAction("Display");
                        }
                        else
                            ModelState.AddModelError("", "Something went wrong while uploading timetable. " +
                                "\n Please make sure your have uploaded your personal timetable");
                    }
                    else
                        ModelState.AddModelError("", "Only pdf files allowed");
                }
                else
                    ModelState.AddModelError("", "Chosen file is too large");
            }
            else
            {
                if (startBlank.Count() != 0)
                    return StartBlank();
                else
                    ModelState.AddModelError("", "No file was uploaded. Please upload file or select to continue without uploading.");
            }

            return View();
        }
        [HttpPost]
        public IActionResult ClearTable(int id)
        {
            Timetable table = _repository.Timetable.GetUserTimetable(User.Identity.Name);
            var moduleColor = _repository.ModuleColor.GetByCondition(m => m.Username == User.Identity.Name);
            if (table != null)
            {
                _repository.Timetable.Delete(table);

            }
            if (moduleColor != null)
            {
                foreach (var item in moduleColor)
                {
                    _repository.ModuleColor.Delete(item);
                }
            }
            _repository.SaveChanges();
            if (id == 0)
                return StartBlank();
            return RedirectToAction("Upload");
        }
        public ActionResult Print()
        {
            int latestPeriod = int.Parse(Request.Cookies["latestPeriod"]);
            #region For Control
            List<List<Session>> ClashesList;
            List<Lecture> GroupedList;
            #endregion

            Timetable table_ = _repository.Timetable.GetUserTimetable(User.Identity.Name);

            if (table_ == null)
                return RedirectToAction("Upload");

            TimetableProcessor processor = new TimetableProcessor(table_.TimetableText, Request.Cookies["isForFirstSemester"] == "true");
            Session[,] data = processor.GetSessionsArray(out ClashesList, out GroupedList);
            Session[,] Model = data;

            // Create a PDF document
            using (PdfDocument document = new PdfDocument())
            {

Bongo/Areas/TimetableArea/Views/Shared/_TimetableAreaLayout.cshtml
<!DOCTYPE html>
<html lang="en">
@{
    string activeController = ViewContext.RouteData.Values["controller"].ToString();
    string activeAction = ViewContext.RouteData.Values["action"].ToString();
    string disableLink = activeAction == "Groups" || activeAction == "Clashes"
    || activeAction == "Upload" ? "disabled" : "";
}

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="google-site-verification" content="MKcm_FRrdGaDSj2_CHSXetlbYVvmnVYiCSCuFVRQ2UQ" />
    <meta name="description" content="Bongo is a web app designed to simplify the process of creating timetables for students. Our goal is to help you optimize your schedule and make the most out of your academic journey.">
    <meta name="keywords" content="Bongo, timetable, scheduling, students, academic, optimization, web app, UFS">
    <meta name="author" content="Bongo">
    <meta name="robots" content="index, follow">
    <meta name="google-site-verification" content="MKcm_FRrdGaDSj2_CHSXetlbYVvmnVYiCSCuFVRQ2UQ" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@ViewData["Title"] - Bongo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/timetableArea.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bongo.styles.css" asp-append-version="true" />
    <link rel="stylesheet" asp-href-include="/lib/font-awesome/css/all.min.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
    <link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16.png">
    <link rel="manifest" href="/images/site.webmanifest">
</head>
<body>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-sm navbar-light shadow">
            <a asp-action="Index" asp-controller="Home" asp-area="" class="navbar-brand logo fs-1">Bongo</a>
            <button class="navbar-toggler d-lg-none"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#collapsibleNavId"
                    aria-controls="collapsibleNavId"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon text-dark"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavId">
                <ul class="navbar-nav ms-auto me-3 mt-2 mt-lg-1">
                    @if ((activeController != "Home" && activeAction != "Index") || activeController == "Merger")
                    {
                        <li class="nav-item me-2">
                            <a asp-action="Index" asp-controller="Home" asp-area="" class="nav-link">HOME</a>
                        </li>
                    }
                    <li class="nav-item">
                        @if (activeController == "Merger")
                        {
                            <a asp-area="TimetableArea" asp-controller="Timetable" asp-action="Upload" class="nav-link">
                                MY TIMETABLE
                            </a>
                        }
                        else
                        {
                            <a asp-area="TimetableArea" asp-controller="Merger" asp-action="ChooseSemester" class="nav-link">
                                MERGE WITH FRIENDS
                            </a>
                        }
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto mt-2 mt-lg-1">
                    <li class="nav-item">
                        <a asp-controller="Account" asp-action="Logout" asp-area=""
                           class="nav-link">Logout</a>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="container-md pt-3">
            <div class="d-flex mt-4">
                @if (activeController == "Timetable" || activeController == "Session")
                {
                    <div class="d-flex flex-column flex-shrink-0 bg-light rounded-3 shadow side-bar" style="height:fit-content;">
                        <ul class="nav nav-xs-tabs nav-pills flex-column text-dark">
                            <li class="nav-item mt-3">
                                <a asp-action="Display" asp-controller="Timetable" class="nav-link sidebar-nav-link text-dark @disableLink
                                        @(activeAction == "Display" && activeController=="Timetable" ? "active" : "")">
                                    <i class="fa-solid fa-home me-2"></i><span>View table</span>
                                </a>
                            </li>
                            <li class="nav-item mt-3">
                                <a asp-action="ManageModules" asp-controller="Session" class="nav-link sidebar-nav-link text-dark @disableLink @(activeAction == "ManageModules" ? "active" : "")">
                                    <i class="fa-solid fa-book me-2"></i><span>Modules</span>
                                </a>
                            </li>
                            <li class="nav-item mt-3">
                                <form asp-controller="Timetable" asp-action="ClearTable" asp-route-id="1" method="post">
                                    <button class="nav-link sidebar-nav-link border-0 w-100 text-start text-dark @(activeAction == "Upload" && activeController=="Timetable" ? "active" : "")"
                                            onclick="return confirm('Are you sure you want to Re-Upload? All saved data will be lost 🙉')">
                                        <i class="fa-solid fa-upload me-2"></i><span>Re-Upload</span>
                                    </button>
                                </form>
                            </li>
                            <li class="nav-item mt-3">
                                <form asp-controller="Timetable" asp-action="ClearTable" asp-route-id="0" method="post">
                                    <button class="nav-link sidebar-nav-link border-0 w-100 text-start text-dark @disableLink" type="submit"
                                            onclick="return confirm('Are you sure you want to Clear table?, All saved data will be lost 🙉')">
                                        <i class="fa-solid fa-broom me-2"></i><span>Clear</span>
                                    </button>
                                </form>
                            </li>
                            <li class="mt-3 mb-2">
                                <a asp-controller="Timetable" asp-action="Print" asp-route-latestPeriod="@Context.Request.Cookies["latestPeriod"]"
                                   class="nav-link sidebar-nav-link text-dark @disableLink @(activeAction == "GeneratePdf" && activeController=="Home" ? "active" : "")" target=" _blank">
                                    <i class="fa-solid fa-download me-2"></i><span>Download</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                }
                <div class="ms-5 main-content position-relative">
                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>
                </div>
            </div>
        </div>
    </div>
    <footer class="border-top fixed-bottom bg-white footer text-muted">
        <div class="container text-center">
            &copy; 2023 - Bongo
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>

Bongo/Areas/TimetableArea/Views/Shared/_ToolsNavBarPartial.cshtml
@{
    string semester = ViewBag.isForFirstSemester ? "1" : "2";
    string isHidden = Context.Request.Cookies["isVenueHidden"];
    string timeSingle = Context.Request.Cookies["isTimeSingle"];
}

<div class="d-flex mb-3 justify-content-between bg-light toolbar-nav">
    <ul class="nav toolbar justify-content-center">
        <li class="nav-item">
            <a class=" text-dark nav-link" title="Edit Colors"
               asp-controller="Session" asp-action="EditColors" asp-route-firstSemester="@TempData["isForFirstSemester"]">
                <i class="fa-solid fa-edit"></i> Colors
            </a>
        </li>
        <li class="nav-item">
            <a class=" text-dark nav-link" title="Edit Groups"
               asp-controller="Session" asp-action="EditGroups" asp-route-firstSemester="@TempData["isForFirstSemester"]">
                <i class="fa-solid fa-edit"></i> Groups
            </a>
        </li>
        <li class="nav-item">
            <a class=" text-dark nav-link" title="Edit Clashes"
               asp-controller="Session" asp-action="EditClashes" asp-route-firstSemester="@TempData["isForFirstSemester"]">
                <i class="fa-solid fa-edit"></i> Clashes
            </a>
        </li>
        <li class="nav-item">
            <form asp-controller="Timetable" asp-action="UpdateCookie"
                  asp-route-key="isVenueHidden" asp-route-value="@(isHidden == "false" ? "true" : "false")" method="post">
                <button class="border-0 text-dark nav-link toogle-btn" title="@(isHidden == "false" ? "Hide Venues" : "Show Venues")" type="submit" style="">
                    <i class="fa-solid @(isHidden == "true" ? "fa-toggle-off" : "fa-toggle-on")"></i> Venue
                </button>
            </form>
        </li>
        <li class="nav-item">
            <form asp-controller="Timetable" asp-action="UpdateCookie"
                  asp-route-key="isTimeSingle" asp-route-value="@(timeSingle == "false" ? "true" : "false")" method="post">
                <button class="border-0 text-dark nav-link toogle-btn" title="@(timeSingle == "false" ? "Disable time intervals" : "Enable time intervals")"
                        type="submit" style="">
                    <i class="fa-solid @(timeSingle == "true" ? "fa-toggle-off" : "fa-toggle-on")"></i> Time-Intervals
                </button>
            </form>
        </li>
        <li class="nav-item dropdown d-md-none">
            <a class="nav-link text-dark dropdown-toggle" href="#" id="dropdownId" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa-solid fa-arrows-rotate me-1"></i>Semester @semester
            </a>
            <ul class="dropdown-menu dropdown-menu-end text-small shadow position-absolute" aria-labelledby="dropdownUser2">
                <li>
                    <form asp-controller="Timetable" asp-action="UpdateCookie"
                          asp-route-key="isForFirstSemester" asp-route-value="@((!ViewBag.isForFirstSemester).ToString().ToLower())" method="post">
                        <button class="text-dark nav-link border-0 toogle-btn" title="Switch between Semester 1 and 2">
                            Semester @(semester == "1" ? "2" : "1")
                        </button>
                    </form>
                </li>
            </ul>
        </li>
    </ul>
    <ul class="nav toolbar d-none d-md-flex">
        <li class="nav-item dropdown">
            <a class="nav-link text-dark dropdown-toggle" href="#" id="dropdownId" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa-solid fa-arrows-rotate me-1"></i>Semester @semester
            </a>
            <ul class="dropdown-menu dropdown-menu-end text-small shadow position-absolute" aria-labelledby="dropdownUser2">
                <li>
                    <form asp-controller="Timetable" asp-action="UpdateCookie"
                          asp-route-key="isForFirstSemester" asp-route-value="@((!ViewBag.isForFirstSemester).ToString().ToLower())" method="post">
                        <button class="text-dark nav-link border-0 toogle-btn" title="Switch between Semester 1 and 2">
                            Semester @(semester == "1" ? "2" : "1")
                        </button>
                    </form>
                </li>
            </ul>
        </li>
    </ul>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {

        var hideElements = document.querySelectorAll('.hide-venue');
        var moduleCode = document.querySelectorAll('.period-button');
        var isHidden = @Html.Raw(Json.Serialize(isHidden));

        if (isHidden === 'true') {
            hideElements.forEach(function (element) {
                element.style.display = 'none';
            });
            moduleCode.forEach(function (x) {
                x.style.verticalAlign = 'middle';
            });
        } else {
            hideElements.forEach(function (element) {
                element.style.display = 'block';
            });
        }
    });
</script>