Bongo/Areas/TimetableArea/Controllers/MergerController.cs
using Bongo.Areas.TimetableArea.Infrastructure;
using Bongo.Areas.TimetableArea.Models;
using Bongo.Areas.TimetableArea.Models.ViewModels;
using Bongo.Data;
using Bongo.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Bongo.Areas.TimetableArea.Controllers
{
    [Authorize]
    [Area("TimetableArea")]
    public class MergerController : Controller
    {
        private static IRepositoryWrapper repository;
        private static UserManager<BongoUser> userManager;
        private static TimetableProcessor processor;
        private static bool _isForFirstSemester;
        private static List<List<Session>> clashes;
        private static List<Lecture> groups;
        private static List<string> mergedUsers;
        private static Session[,] mergedSessions;
        public MergerController(IRepositoryWrapper _repository, UserManager<BongoUser> _userManager)
        {
            repository = _repository;
            userManager = _userManager;
        }
        public IActionResult ChooseSemester()
        {
            return View();
        }
        public IActionResult SetSemester(bool isForFirstSemester)
        {
            _isForFirstSemester = isForFirstSemester;
            mergedUsers = new();
            return RedirectToAction("ReviewCurrentUser");
        }
        public IActionResult ReviewCurrentUser()
        {
            var timetabe = repository.Timetable.GetUserTimetable(User.Identity.Name);
            if (timetabe != null)
                return RedirectToAction("AddUserTimetable", new { username = User.Identity.Name });

            TempData["Message"] = "Please create your timetable before you can merge with others.";
            return RedirectToAction("Upload", "Timetable");
        }
        public IActionResult Index()
        {
            var usersKeyValuePairs = (IEnumerable<KeyValuePair<string, string>>)userManager.Users
                .Select(user => new KeyValuePair<string, string>(user.UserName, user.MergeKey));

            var users = new Dictionary<string, string>(usersKeyValuePairs);
            users.Remove(User.Identity.Name);

            return View(new MergerIndexViewModel
            {
                Sessions = mergedSessions,
                MergedUsers = mergedUsers,
                Users = users
            });
        }
        public IActionResult AddUserTimetable(string username)
        {
            if (mergedUsers.Contains(username))
            {
                TempData["Message"] = $"{username}'s timetable has already been merged with.";
            }
            else
            {
                var timetable = repository.Timetable.GetUserTimetable(username);
                if (timetable != null)
                {
                    if (timetable.TimetableText == "")
                    {
                        TempData["Message"] = $"Please note {username}'s timetable is empty. It has no classes, practicals or tutorials.";
                        goto AddUser;
                    }

                    processor = new TimetableProcessor(timetable.TimetableText, _isForFirstSemester);
                    Session[,] newUserSessions = processor.GetSessionsArray(out clashes, out groups);

                    if (clashes.Count > 0 || groups.Count > 0)
                    {
                        if (username == User.Identity.Name)
                        {
                            TempData["Message"] = "Please ensure that you have managed your clashes and/groups before merging with others.";

                            CookieOptions cookieOptions = new CookieOptions { Expires = DateTime.Now.AddDays(90) };
                            Response.Cookies.Append("isForFirstSemester", _isForFirstSemester.ToString(), cookieOptions);
                            return RedirectToAction("Manage", "Session");
                        }
                        else
                        {
                            TempData["Message"] = $"Could not merge with {username}'s timetable.\n" +
                                $"Please ensure that {username} has managed their clashes and/or groups before merging with them.";
                            return RedirectToAction("Index");
                        }
                    }
                    if (mergedUsers.Count == 0)
                        mergedSessions = newUserSessions.SplitSessions();
                    else
                        MergerControlHelpers.Merge(mergedSessions, newUserSessions);

                    AddUser:
                    mergedUsers.Add(username);
                    return RedirectToAction("Index");
                }

                TempData["Message"] = $"Could not merge with {username}'s timetable.\n" +
                                $"Please ensure that {username} has created their timetable before merging with them.";
            }

            return RedirectToAction("Index");
        }
        public IActionResult RemoveUserTimetable(string username)
        {
            if (mergedUsers.Contains(username))
            {
                var timetable = repository.Timetable.GetUserTimetable(username);
                if (timetable.TimetableText != "")
                {
                    processor = new TimetableProcessor(timetable.TimetableText, _isForFirstSemester);
                    MergerControlHelpers.UnMerge(mergedSessions, processor.GetSessionsArray(out clashes, out groups));
                }
                mergedUsers.Remove(username);
            }
            return RedirectToAction("Index");
        }
    }
}

Bongo/Controllers/HomeController.cs
using Bongo.Data;
using Bongo.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Bongo.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly UserManager<BongoUser> _userManager;
        private readonly IRepositoryWrapper _repo;

        public HomeController(IRepositoryWrapper repo, UserManager<BongoUser> userManager)
        {
            _repo = repo;
            _userManager = userManager;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                TempData["HasTimetable"] = _repo.Timetable.GetUserTimetable(User.Identity.Name) != null;
                var user = await _userManager.FindByNameAsync(User.Identity.Name);
                if (user.MergeKey == default)
                    return RedirectToAction("MergeKey", "Account");
            }
            else
                TempData["HasTimetable"] = false;

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Notice()
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            user.Notified = true;
            await _userManager.UpdateAsync(user);
            Response.Cookies.Append("Notified", user.Notified.ToString().ToLower(),
                            new CookieOptions { Expires = DateTime.Now.AddDays(90) }
                            );
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Profile()
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            return View(user);
        }
        [HttpPost]
        [ActionName("Profile")]
        public async Task<IActionResult> UpdateProfile(string id, string action, string newValue)
        {
            BongoUser user = await _userManager.FindByNameAsync(User.Identity.Name);

            switch (id)
            {
                case "username": user.UserName = newValue; break;
                case "email": user.Email = newValue; break;
                case "mergeKey": user.MergeKey = newValue; break;
            }

            var result = await _userManager.UpdateAsync(user);
            if (result.Succeeded)
                TempData["Message"] = "Your account detail(s) have successfully been updated";
            else
                TempData["Message"] = "Failed to update account detail(s)";

            return action == "mergeKey" ? RedirectToAction("Index") : RedirectToAction("Profile");
        }
    }
}

Bongo/Views/Home/AboutUs.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Bongo/Views/Home/Donate.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Bongo/Views/Home/Index.cshtml
<div class="home-menu">
    <div class="half-menu">
        <div class="m-1 menu-card">
            <a asp-area="TimetableArea" asp-controller="Timetable" asp-action="Upload"
               title="Create timetable" class="">
                <div>
                    <div class="icon">
                        <i class="fa-solid fa-table text-warning"></i>
                    </div>
                    @if (TempData["HasTimetable"].ToString().ToLower() == "true")
                    {
                        <h4>View timetable</h4>
                        <div class="">
                            <p>View, manage, or download  your timetable. Add or remove sessions, manage groups and clashes.</p>
                        </div>
                    }
                    else
                    {
                        <h4>Create timetable</h4>
                        <div class="">
                            <p>Easily create your timetable from your UFS personal timetable or from scratch.</p>
                        </div>
                    }
                </div>
            </a>
        </div>
        <div class="m-1 menu-card">
            <a asp-area="TimetableArea" asp-controller="Merger" asp-action="ChooseSemester"
               title="Merge timetables" class="">
                <div>
                    <div class="icon">
                        <i class="fa-solid fa-object-ungroup text-danger"></i>
                    </div>
                    <h4>Merge timetables</h4>
                    <div class="">
                        <p>Know the times when you and your friends are all free by merging your Bongo timetables.</p>
                    </div>
                </div>
            </a>
        </div>
    </div>
    <div class="half-menu mt-1">
        <div class="m-1 menu-card">
            <a title="Coming soon">
                <div>
                    <div class="icon">
                        <i class="fa-solid fa-chalkboard-user text-success"></i>
                    </div>
                    <h4>Find a tutor</h4>
                    <div class="">
                        <p>Need a tutor? Tell us the module and we will find a tutor for you to help with your academic needs.</p>
                    </div>
                </div>
            </a>
        </div>
        <div class="m-1 menu-card">
            <a title="Coming soon">
                <div>
                    <div class="icon">
                        <i class="fa-solid fa-person-chalkboard text-primary"></i>
                    </div>
                    <h4>Be a tutor</h4>
                    <div class="">
                        <p>Have a module you excelled in? Then apply to be one of our excellent tutors on standby and use your skills to your benefit and the benefit of others.</p>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>

@if (Context.Request.Cookies["Notified"] == "false")
{
    <!-- Modal -->
    <div class="modal fade " id="noticeModal" tabindex="-1" aria-labelledby="termsModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-scrollable">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title text-center" id="staticBackdropLabel">Important Notice</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body terms-modal">
                    <p>
                        Dear @User.Identity.Name😊,
                    </p>

                    <p>We would like to express our heartfelt gratitude for choosing Bongo for your needs. We strive to provide the best experience and service to our users.</p>

                    <p>
                        Currently, we are making some important updates to improve our services. During this period, you may encounter certain features that are temporarily unavailable. We also recommend that you use desktop (laptop) for better exeperience. We sincerely apologize for any inconvenience this may cause.
                    </p>
                    <p>
                        If you encounter any issues or have any questions, please do not hesitate to contact our support team. We are here to assist you and ensure that your experience with Bongo is as seamless as possible.
                    </p>
                    <p>Thank you for your understanding and continued support.<br /></p>

                    <p> Best regards,<br />The Bongo Team</p>

                </div>
                <div class="modal-footer">
                    <form asp-controller="Home" asp-action="Notice" method="post">
                        <button type="submit" class="btn btn-secondary" data-bs-dismiss="modal">Continue</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
}

Bongo/Views/Home/Profile.cshtml
@model BongoUser

@{
    ViewData["Title"] = "Profile";
}

@if (TempData["Message"] != null)
{
    <div class="alert alert-warning alert-dismissible fade show alert-table" role="alert">
        <i class="fa-solid fa-check"></i>
        @TempData["Message"]
    </div>
}
<div class="account-forms mt-4 p-3 shadow" style="width:330px;justify-self:center; height:fit-content;">
    <div class="profile-part">
        <h5>Username:</h5>
        <div class="mb-1 ms-2">
            <div>@Model.UserName</div>
            <button onclick="update('changeUsername')" class="btn ms-1">
                <i class="fa-solid text-warning fa-pen-to-square"></i>
            </button>
        </div>
        <div id="changeUsername" hidden>
            <form asp-action="Profile" asp-route-id="username" method="post">
                <input name="newValue" class="form-control me-2" required placeholder="Enter new username" />
                <button type="submit" class="btn btn-outline-success me-1">Save</button>
                <button title="cancel" class="btn" type="button" onclick="closeDiv('changeUsername')">
                    <i class="fa-solid fa-xmark"></i>
                </button>
            </form>
        </div>
    </div>
    <div class="profile-part">
        <h5>Email:</h5>
        <div class="mb-1 ms-2">
            <div>@Model.Email</div>
            <button onclick="update('changeEmail')" class="btn ms-1">
                <i class="fa-solid text-warning fa-pen-to-square"></i>
            </button>
        </div>
        <div id="changeEmail" hidden>
            <form asp-action="Profile" asp-route-id="email" method="post">
                <input name="newValue" type="email" class="form-control me-2" required placeholder="Enter new email" />
                <button type="submit" class="btn btn-outline-success me-1">Save</button>
                <button title="cancel" class="btn" type="button" onclick="closeDiv('changeEmail')">
                    <i class="fa-solid fa-xmark"></i>
                </button>
            </form>
        </div>
    </div>
    <div class="profile-part">
        <h5>Merge Key:</h5>
        <div class="mb-1 ms-2">
            <div>@Model.MergeKey</div>
            <button onclick="update('changeMergeKey')" class="btn ms-1">
                <i class="fa-solid text-warning fa-pen-to-square"></i>
            </button>
        </div>
        <div id="changeMergeKey" hidden>
            <form asp-action="Profile" asp-route-id="mergeKey" method="post">
                <input name="newValue" class="form-control me-2" required placeholder="Enter new key" />
                <button type="submit" class="btn btn-outline-success me-1">Save</button>
                <button title="cancel" class="btn" type="button" onclick="closeDiv('changeMergeKey')">
                    <i class="fa-solid fa-xmark"></i>
                </button>
            </form>
        </div>
    </div>
    <hr />
    <h4>Other</h4>
    <a asp-action="ChangePassword" asp-controller="Account" asp-route-userId="@Model.Id" class="btn btn-link py-1">Change password</a>
    <a asp-action="SecurityQuestion" asp-controller="Account" asp-route-username="@Model.UserName" asp-route-sendingAction="Profile"
       class="btn btn-link py-1 mt-1">
        Change security question and answer
    </a>
</div>