Bongo/Areas/TimetableArea/Controllers/HowItWorksController.cs
using Bongo.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Bongo.Areas.TimetableArea.Controllers
{
    [AllowAnonymous]
    [Area("TimetableArea")]
    public class HowItWorksController : Controller
    {
        private readonly IRepositoryWrapper _repo;

        public HowItWorksController(IRepositoryWrapper repo)
        {
            _repo = repo; 
        }
        public IActionResult CreateTimetable()
        {
            return View(_repo.UserReview.FindAll().ToList());
        }
        public IActionResult MergeTimetables()
        {
            return View();
        }
    }
}

Bongo/Areas/TimetableArea/Controllers/SessionController.cs
using Bongo.Areas.TimetableArea.Infrastructure;
using Bongo.Areas.TimetableArea.Models;
using Bongo.Areas.TimetableArea.Models.ViewModels;
using Bongo.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text.RegularExpressions;

namespace Bongo.Areas.TimetableArea.Controllers
{
    [Authorize]
    [Area("TimetableArea")]
    public class SessionController : Controller
    {
        private IRepositoryWrapper _repository;
        private static Timetable table;
        private List<List<Session>> ClashesList;
        private List<Lecture> GroupedList;
        private static bool firstSemester;
        private static TimetableProcessor processor;
        private static Session[,] data;

        public SessionController(IRepositoryWrapper repository)
        {
            _repository = repository;
        }
        private void Initialise(bool isForFirstSemester)
        {
            firstSemester = isForFirstSemester;
            table = _repository.Timetable.GetUserTimetable(User.Identity.Name);
            processor = new TimetableProcessor(table.TimetableText, isForFirstSemester);
            data = processor.GetSessionsArray(out ClashesList, out GroupedList);
        }

        public IActionResult Manage()
        {
            bool isForFirstSemester = Request.Cookies["isForFirstSemester"] == "true";
            Initialise(isForFirstSemester);
            MarkDisabled();

            if (ClashesList.Count > 0)
                return View("Clashes", ClashesList);
            if (GroupedList.Count > 0)
                return View("Groups", new GroupsViewModel { GroupedLectures = GroupedList });

            TempData["isForFirstSemester"] = isForFirstSemester;
            return RedirectToAction("Display", "Timetable");
        }
        [HttpPost]
        public IActionResult Clashes(string[] Sessions)
        {
            RemoveSelectedWhereNecessary("class");

            foreach (string session in Sessions)
            {
                if (SessionControlHelpers.ContainsClashes(Sessions))
                {
                    ModelState.AddModelError("", "You have selected clashing sessions");
                    return View(processor.GetClashingSessions());
                }

                if (session is not null)
                {
                    if (!session.Contains("Tap to handle") || (session.Contains("Tap to handle") && table.TimetableText.Contains(session)))
                        table.TimetableText = table.TimetableText.
                            Replace(session, session + "selectedClass");
                    else
                    {
                        Regex timepattern = new Regex(@"[\d]{2}:[\d]{2} [\d]{2}:[\d]{2}");
                        Regex daypattern = new Regex(@"Monday|Tuesday|Wednesday|Thursday|Friday");
                        Match timeMatch = timepattern.Match(session);
                        string startTime = timeMatch.Value.Substring(0, 5);
                        string endTime = timeMatch.Value.Replace(startTime + " ", "");
                        int semesterNo = Request.Cookies["isForFirstSemester"] == "true" ? 1 : 2;
                        AddNewSession(new AddSessionViewModel
                        {
                            ModuleCode = $"CCCC12{semesterNo}3",
                            SessionType = "Lecture",
                            SessionNumber = 1,
                            startTime = startTime,
                            endTime = endTime,
                            Day = $"{daypattern.Match(session).Value}selectedClass",
                            Venue = "Tap to handle"

                        });
                    }

                }
            }
            UpdateAndSave();

            return RedirectToAction("Manage");
        }

        [HttpPost]
        public IActionResult Groups(GroupsViewModel model)
        {
            List<Lecture> grouped = processor.GetGroupedLectures();
            List<string> sessions = new List<string>(model.Sessions);

            RemoveSelectedWhereNecessary("ignored", grouped);
            if (model.Ignore != null)
                foreach (string s in model.Ignore)
                {
                    table.TimetableText = table.TimetableText.Replace(s, s + "ignored");
                    sessions.Remove(s);
                }

            string[] strings = SessionControlHelpers.GetClashing(sessions.ToArray());
            if (strings.Count() > 0)
            {
                foreach (string item in strings)
                {
                    sessions.Remove(item);
                }
            }

            List<Lecture> clashing = new();
            List<Lecture> unclashing = new();

            if (strings.Length > 0)
            {
                foreach (var session in strings)
                {
                    foreach (var lect in grouped)
                    {
                        if (lect.sessions.Select(l => l.sessionInPDFValue).Contains(session))
                        {
                            clashing.Add(lect);
                        }
                        else
                            unclashing.Add(lect);

                    }
                }
            }

            RemoveSelectedWhereNecessary("group", unclashing);

            foreach (string session in sessions)
            {
                if (session is not null)
                {
                    Lecture sessionLecture = grouped.FirstOrDefault(lect => lect.sessions.Select(s => s.sessionInPDFValue).Contains(session));
                    if (model.SameGroups != null && model.SameGroups.Contains($"{sessionLecture.ModuleCode} {sessionLecture.LectureDesc}"))
                    {
                        Regex groupPattern = new Regex(@"Group [A-Z]{1,2}[\d]?");
                        foreach (Session s in sessionLecture.sessions)
                            if (groupPattern.Match(s.sessionInPDFValue).Success)
                                table.TimetableText = table.TimetableText.Replace(s.sessionInPDFValue, s.sessionInPDFValue + "selectedGroup");
                    }
                    else
                        table.TimetableText = table.TimetableText.Replace(session, session + "selectedGroup");
                }
            }

            UpdateAndSave();
            if (strings.Length > 0)
            {
                ModelState.AddModelError("", "You have selected clashing sessions. Please ensure you don't select sessions that are clashing with each other or with sessions that are already there.");
                return View(new GroupsViewModel { GroupedLectures = clashing });
            }

            return RedirectToAction("Manage");

        }

        public IActionResult ManageModules()
        {
            PopulateColorDLL();
            var colors = _repository.Color.FindAll();
            var moduleColors = _repository.ModuleColor.GetByCondition(m => m.Username == User.Identity.Name);
            var x = moduleColors.Where(m =>
                 Request.Cookies["isForFirstSemester"] == "true" ? (int.Parse(m.ModuleCode.Substring(6, 1)) == 0 || int.Parse(m.ModuleCode.Substring(6, 1)) % 2 == 1)
                                : int.Parse(m.ModuleCode.Substring(6, 1)) % 2 == 0);
            return View("EditColors", new ModulesColorsViewModel()
            {
                ModuleColors = x,
                Colors = colors
            });
        }

        [HttpPost]
        public IActionResult DeleteModule(string ModuleCode)
        {
            int moduleIndex = table.TimetableText.IndexOf(ModuleCode);
            if (moduleIndex != -1)
            {
                Regex modPattern = new Regex(@"[A-Z]{4}[\d]{4}");
                Match nextModule = modPattern.Match(table.TimetableText.Substring(moduleIndex + ModuleCode.Length));
                if (nextModule.Success)
                {
                    int nextModuleIndex = moduleIndex + nextModule.Index;
                    string whole = table.TimetableText.Substring(moduleIndex, nextModuleIndex - moduleIndex);
                    table.TimetableText = table.TimetableText.Replace(whole, "");
                }
                else
                    table.TimetableText = table.TimetableText.Replace(table.TimetableText.Substring(moduleIndex), "");

                var moduleColor = _repository.ModuleColor.FindAll().FirstOrDefault(mc => mc.Username == User.Identity.Name && mc.ModuleCode == ModuleCode);
                _repository.ModuleColor.Delete(moduleColor);

                UpdateAndSave();
                TempData["Message"] = "Module removed successfuly💃🏿";
            }
            return RedirectToAction("ManageModules");
        }
        public IActionResult EditClashes(bool firstSemester, string session = "")
        {
            firstSemester = Request.Cookies["isForFirstSemester"] == "true";
            Initialise(firstSemester);
            TempData["isForFirstSemester"] = firstSemester;
            List<List<Session>> clashes = session == "" ? processor.GetClashingSessions(true) : processor.GetSpecificClashes(session);
            return View("Clashes", clashes);
        }
        public IActionResult EditGroups(bool firstSemester)
        {
            firstSemester = Request.Cookies["isForFirstSemester"] == "true";
            Initialise(firstSemester);
            TempData["isForFirstSemester"] = firstSemester;
            return View("Groups", new GroupsViewModel { GroupedLectures = processor.GetGroupedLectures(true, true) });
        }
        [HttpPost]
        public IActionResult DeleteSession(string session, bool firstSemester)
        {
            if (session != null)
            {
                //table.TimetableText.Trim();
                string[] timeLines = table.TimetableText.Split("\n");

                List<string> rem = new List<string>();


                int x = 0;

Bongo/Areas/TimetableArea/Controllers/UserReviewController.cs
using Bongo.Areas.TimetableArea.Models;
using Bongo.Areas.TimetableArea.Models.User;
using Bongo.Data;
using Bongo.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Bongo.Areas.TimetableArea.Controllers
{
    [Authorize]
    [Area("TimetableArea")]
    public class UserReviewController : Controller
    {
        private readonly IRepositoryWrapper _repo;
        private readonly UserManager<BongoUser> _userManager;

        public UserReviewController(IRepositoryWrapper repo, UserManager<BongoUser> userManager)
        {
            _repo = repo;
            _userManager = userManager;
        }

        [HttpGet]
        public IActionResult AddReview()
        {
            UserReview model = _repo.UserReview.FindAll().FirstOrDefault(r => r.Username == User.Identity.Name);
            return View(model ?? new UserReview { Username = User.Identity.Name});
        }
        [HttpPost]
        public async Task<IActionResult> AddReview(UserReview model)
        {
            try
            {
                var user = await _userManager.FindByNameAsync(model.Username);
                model.ReviewDate = DateTime.Now.ToLocalTime();
                model.Email = user.Email;
                if (model.ReviewId != 0)
                {
                    _repo.UserReview.Update(model);
                    TempData["Message"] = "Review updated successfully. Thank you";
                }
                else
                {
                    _repo.UserReview.Create(model);
                    TempData["Message"] = "Review submited successfully. Thank you";
                }
                _repo.SaveChanges();
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Someting went wrong while saving. Please try again later.😔");
            }
            var newModel = _repo.UserReview.FindAll().FirstOrDefault(r => r.Username.Equals(model.Username));   
            return View(newModel ?? model);
        }
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult ListReviews()
        {
            return View(_repo.UserReview.FindAll().OrderBy(u => u.Username));
        }
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public ActionResult ListUsers()
        {
            return View(_userManager.Users.OrderBy(u => u.UserName));
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(string id)
        {
            var user = _userManager.Users.FirstOrDefault(u => u.Id == id);
            if (user != null)
            {
                try
                {
                    await _userManager.DeleteAsync(user);
                    IEnumerable<ModuleColor> moduleColors = _repo.ModuleColor.GetByCondition(mc => mc.Username == user.UserName);
                    foreach (var module in moduleColors)
                        _repo.ModuleColor.Delete(module);
                    var table = _repo.Timetable.FindAll().FirstOrDefault(t => t.Username == user.UserName);
                    if (table != null)
                        _repo.Timetable.Delete(table);

                    _repo.SaveChanges();
                    TempData["Message"] = $"{user.UserName} has been deleted successfully!";
                }
                catch (Exception e)
                {
                    TempData["Message"] = $"Something went wrong!\nMessage: {e.ToString()}";
                }
            }
            return RedirectToAction("ListUsers");
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public IActionResult DeleteReview(string username)
        {
            var userReview = _repo.UserReview.FindAll().FirstOrDefault(ur => ur.Username == username);
            if (userReview != null)
            {
                try
                {
                    _repo.UserReview.Delete(userReview);

                    _repo.SaveChanges();
                    TempData["Message"] = $"{username}'s review has been deleted successfully!";
                }
                catch (Exception e)
                {
                    TempData["Message"] = $"Something went wrong!\nMessage: {e.ToString()}";
                }
            }
            return RedirectToAction("ListReviews");
        }
    }
}

Bongo/Areas/TutoringArea/Controllers/HowItWorksController.cs
using Bongo.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Bongo.Areas.TutoringArea.Controllers
{
    [AllowAnonymous]
    [Area("TutoringArea")]
    public class HowItWorksController : Controller
    {
        private readonly IRepositoryWrapper _repo;

        public HowItWorksController(IRepositoryWrapper repo)
        {
            _repo = repo; 
        }
        public IActionResult FindTutor()
        {
            return View();
        }
        public IActionResult BeTutor()
        {
            return View();
        }
    }
}

Bongo/Areas/TimetableArea/Views/HowItWorks/CreateTimetable.cshtml
@*<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="Bongo is a web app designed to simplify the process of creating timetables for students. Our goal is to help you optimize your schedule and make the most out of your academic journey.">
    <meta name="keywords" content="Bongo, timetable, scheduling, students, academic, optimization, web app, UFS">
    <meta name="author" content="Bongo">
    <meta name="robots" content="index, follow">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Bongo</title>
    <title>Bongo - Create Your Timetable</title>

    <link rel="stylesheet" href="/css/landingPage.css" />
    <link rel="stylesheet" asp-href-include="/lib/font-awesome/css/all.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous" />

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap"
          rel="stylesheet" />
    <link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16.png">
    <link rel="manifest" href="/images/site.webmanifest">

</head>
<body class="">
    <section class="main-section container px-5">
        <div class="row mx-md-5">
            <div class="col-lg-6 mb-4">
                <h1>
                    Are you a Student tired of manually drafting your timetable every
                    semester?
                </h1>
                <p class="header-text">
                    Say no more, because Bongo will help you create your timetable in
                    just a few seconds.
                </p>
                <div class="w-100 text-center mb-4">
                    <a class="btn btn-outline-primary ms-auto"
                       asp-controller="Session" asp-action="TimeTableFileUpload" style="width: 180px !important;">@(User.Identity.IsAuthenticated ? "Back to Home" : "GetSessionsArray started")</a>
                </div>
            </div>
            <div class="col-lg-6 top-image">
                <img src="/images/top-image.gif" alt="image" />
            </div>
        </div>
    </section>

    <section class="how-it-works-section py-5 position-relative" id="how-it-works-section">
        <div class="break-section">
            😏
        </div>
        <div class="container pt-5">
            <h1 class="section-heading w-100 text-center text-primary fs-1">
                How It Works
            </h1>
            <p class="section-content mt-5 px-5 text-center">
                With Bongo, you can easily create and manage your personalized
                timetable. Just follow these simple steps:
            </p>
            <p class="section-content mt-5 px-5 text-danger text-center">
                ⚠ Please note that we'll never ask you of your student portal
                credentials. ⚠
            </p>
            <div id="carouselExampleDark"
                 class="carousel carousel-dark slide mb-5"
                 data-bs-ride="carousel">
                <div class="carousel-indicators">
                    <button type="button"
                            data-bs-target="#carouselExampleDark"
                            data-bs-slide-to="0"
                            class="active"
                            aria-current="true"
                            aria-label="Slide 1"></button>
                    <button type="button"
                            data-bs-target="#carouselExampleDark"
                            data-bs-slide-to="1"
                            aria-label="Slide 2"></button>
                    <button type="button"
                            data-bs-target="#carouselExampleDark"
                            data-bs-slide-to="2"
                            aria-label="Slide 3"></button>
                    <button type="button"
                            data-bs-target="#carouselExampleDark"
                            data-bs-slide-to="3"
                            aria-label="Slide 4"></button>
                   
                </div>
                <div class="carousel-inner">
                    <div class="carousel-item active" data-bs-interval="10000">
                        <img src="images/how-to-use/step1.jpg"
                             class="d-block w-100"
                             alt="step1" />
                        <div class="carousel-caption">
                            <h5>Step 1</h5>
                            <p>Log into your student portal. Go to Student center.</p>
                        </div>
                    </div>
                    <div class="carousel-item" data-bs-interval="2000">
                        <img src="/images/how-to-use/step2.jpg"
                             class="d-block w-100"
                             alt="step2" />
                        <div class="carousel-caption">
                            <h5>Step 2</h5>
                            <p>Go to student documentation.</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="/images/how-to-use/step3.jpg"
                             class="d-block w-100"
                             alt="step3" />
                        <div class="carousel-caption">
                            <h5>Step 3</h5>
                            <p>Print your class timetable.</p>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <img src="/images/how-to-use/step4.jpg"
                             class="d-block w-100"
                             alt="step4" />
                        <div class="carousel-caption">
                            <h5>Step 4</h5>
                            <p>Upload you class timetable to bongo.</p>
                        </div>
                    </div>
                   
                </div>
                <button class="carousel-control-prev"
                        type="button"
                        data-bs-target="#carouselExampleDark"
                        data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next"
                        type="button"
                        data-bs-target="#carouselExampleDark"
                        data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>
    </section>

    <section class="testimonial-section py-5 position-relative" id="testimonial">
        <div class="break-section">
            🤩
        </div>
        <div class="container">
            <h2 class="section-heading text-center fs-1 mb-5 text-primary">Reviews</h2>
            <div id="carouselExampleInterval"
                 class="carousel slide mt-5 py-5"
                 data-bs-ride="carousel">
                <div class="carousel-inner text-center">
                    @{bool active = true;}
                    @foreach (var review in Model)
                    {
                        <div class="carousel-item @(active ? "active" : " ")" data-bs-interval="5000">
                            <div class="testimonial d-flex flex-column mx-auto">
                                <div class="d-flex">
                                    <div class="testimonial-profile">
                                        <img src="/images/profile.png" alt="testimonial-profile" />
                                    </div>
                                    <div class="testimonial-info mx-3">
                                        <div class="testimonial-author fs-5 fw-bold">@review.Username</div>
                                        <div class="testimonial-rating">
                                            @for (int i = 0; i < review.Rating; i++)
                                            {
                                                <i class="fa-solid fa-star"></i>
                                            }
                                            @for (int i = 0; i < (5 - review.Rating); i++)
                                            {
                                                <i class="fa-regular fa-star"></i>
                                            }
                                        </div>
                                        <div class="testimonial-date">
                                            <span class="text-muted">@review.ReviewDate.AddHours(6).ToShortDateString()</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="testimonial-content" style="margin-left: 77px;">
                                   @review.Review
                                </div>
                            </div>
                        </div>
                        active = false;
                    }
                </div>
                <button class="carousel-control-prev"
                        type="button"
                        data-bs-target="#carouselExampleInterval"
                        data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next"
                        type="button"
                        data-bs-target="#carouselExampleInterval"
                        data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
            <div class="rate-us text-center mt-5 pt-3 text-dark">
                <p class="mb-3 fs-6">We want to hear from you. What are thoughts on the application?</p>
                <a asp-controller="UserReview" asp-action="AddReview" class="btn btn-primary mt-2" style="width: 180px !important;">
                    Review us
                </a>
            </div>
        </div>
    </section>

    <section class="about-section text-center position-relative p-5" id="about-us">
        <div class="break-section">
            😎
        </div>
        <div class="container d-flex justify-content-center">
            <div class="about" id="about">
                <p class="about-content">
                    Bongo is a web app designed to simplify the process of creating
                    timetables for students. Our goal is to help you optimize your
                    schedule and make the most out of your academic journey.
                </p>
                <p>
                    By Stu and Oliver 😎
                </p>
            </div>
        </div>
        <div class="container text-center">
            <div class="footer-contact">
                <p>
                    For any inquiries, please contact us: <a href="mailto:bongospprt@gmail.com"
                                                             class="text-decoration-none">Support Bongo</a>
                </p>
            </div>
        </div>
        <footer class="border-top footer text-muted">
            <div class="container text-center">
                <a class="text-decoration-none text-muted " data-bs-toggle="modal" data-bs-target="#termsModal">
                    Terms and conditions
                </a>
                <a class="text-decoration-none text-muted" data-bs-toggle="modal" data-bs-target="#privacyModal">
                    | Privacy policy
                </a> | &copy; 2023 - Bongo v1
            </div>
        </footer>
    </section>
</body>
</html>

@await Html.PartialAsync("_TermsAndPrivacyModal")

*@

Bongo/Areas/TimetableArea/Views/HowItWorks/MergeTimetables.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}